sudo: required
services:
  - docker

before_install:
  - docker build -t ramakishore/react-app-test -f ./client/Dockerfile.dev  ./client

script:
  - docker run -e CI=true ramakishore/react-app-test npm test -- --coverage

after_success:
  - docker build -t ramakishore/new-client ./client
  - docker build -t ramakishore/new-nginx ./nginx
  - docker build -t ramakishore/new-server ./server
  - docker build -t ramakishore/new-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push ramakishore/new-client
  - docker push ramakishore/new-nginx
  - docker push ramakishore/new-server
  - docker push ramakishore/new-worker

deploy:
  edge: true
  provider: elasticbeanstack
  region: "ap-south-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-ap-south-1-324889265044"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY



